### PR TITLE
Make /home/i2pd mountable as a docker volume

### LINKED ISSUE #5: [BUG] i2pd.conf is always unconditionally overwritten
The README.md says to mount over the `/home/i2pd/conf/` folder, but the `entrypoint.sh` is always unconditionally overwriting the `i2pd.conf` in this folder based on the `/home/i2pd/i2pd.org.conf` template file and then substituting the variables in it.

---

I think the intent was to make the `i2pd.conf` configurable, but it's not at all based on the `entrypoint.sh`.

### LINKED ISSUE #7: [BUG] Host network binding not configurable
Because of https://github.com/diva-exchange/i2p/issues/5, it's not possible to configure any setting that's not exposed explicitly via the `entrypoint.sh`.  

Binding the host network IP that's allowed is a standard feature most users will need.  It's currently not settable.

### PR DESCRIPTION
**Pull request by ShrirajHegde**
- [Make /home/i2pd mountable as a docker volume](https://github.com/ShrirajHegde/i2pd/commit/166a34e777de10bb6019fb1e1d4e54f54bac39ff)
- [Optimize Dockerfile](https://github.com/ShrirajHegde/i2pd/commit/6f41e06f08399c05cbeba85bc617f6d991c28dd3)
- [Move the temporary config file to /tmp](https://github.com/ShrirajHegde/i2pd/commit/07123384b97883db9a4d15c544206b61242e5a19)
[Add PORT_TOR=9950 in Dockerfile so it doesn't need to be manually set in the container](https://github.com/ShrirajHegde/i2pd/commit/829e3607136aa4a0377d97a8427e9b248adaf01d)

Fixes #5 without breaking any previous behaviour.

Also fixes #7. https://github.com/ShrirajHegde/i2pd/commit/166a34e777de10bb6019fb1e1d4e54f54bac39ff#r143904943

### CODE REVIEW

**Comment by ShrirajHegde** [comment]
@diva-exchange Can you provide the `Dockerfile` and `entrypoint.sh` for `divax/i2p:current-i2p-tor` image.

**Comment by diva-exchange** [comment]
https://github.com/diva-exchange/i2p/blob/i2p-tor/Dockerfile

https://github.com/diva-exchange/i2p/blob/i2p-tor/entrypoint.sh

**Comment by ShrirajHegde** [comment]
Hey @diva-exchange, I got the entrypoint.sh from your image and modified the Dockerfile to include tor.

- It is better to keep them in the same branch, as branches are not recommended for this purpose. It is easier to build or maintain using a single branch.

- I have pushed Dockerfile-tor and entrypoint-tor.sh. I have also optimized the Dockerfiles for size and build speed. Build the images and check for yourself. 

- Not only that, but I have carefully made changes that they do not change any behaviors. This is a great image for quickly setting up i2p. I have a few more changes related to config to make it even better.

- When making a push to docker hub next time, consider building multi-platform images like this https://hub.docker.com/r/shrirajhegde/i2pd-tor/tags so it works on ARM platforms too.

Let me know if you want any more information.

**Comment by diva-exchange** [comment]
Thank you - great feedback and great changes. Merged it and will test it with i2pd 2.54.0. One question remains: How to do build multi-platform images? Can this be included in the [build.sh script](https://github.com/diva-exchange/i2p/blob/develop/bin/build.sh)?

**Comment by ShrirajHegde** [comment]
@diva-exchange, yes.

I can build and push by 

```
docker buildx build . \
    --platform linux/arm64,linux/amd64,linux/arm/v7 \
     -t shrirajhegde/i2pd-tor --push -f Dockerfile-tor
```

See that I am specifying all the platform and the specific docker file.
https://hub.docker.com/r/shrirajhegde/i2pd-tor

image

When it's built like this, if you do `shrirajhegde/i2pd-tor:latest`, your system will choose the architecture accordingly with no changes to docker compose or the docker run command.

For non tor variant, I do 

```
docker buildx build . \
    --platform linux/arm64,linux/amd64,linux/arm/v7 \
     -t shrirajhegde/i2pd --push -f Dockerfile
```
https://hub.docker.com/r/shrirajhegde/i2pd/tags

But I would advice you to use GitHub actions like I do. I have set it up to build the image every week automatically. And the new image will be tagged with `latest` and `git-<commit_hash>` of i2pd repo.

It runs weekly at 9AM UTC : https://github.com/ShrirajHegde/i2pd/actions.

**Comment by diva-exchange** [comment]
Great & thanks! Will enable github actions on the main branch. Reason: don't want to push develop branch to docker (since PR's [and also some not-that-well-tested commits] go to develop branch). But tested and approved stuff (which is the main branch) shall be published on docker hub.

**Comment by ShrirajHegde** [comment]
If you need high stability, you need to checkout the latest release tag when building i2pd. 

They might have commits that are not fully ready to be used too.

Let me know if you want to to implement that in the GitHub actions.

**Comment by ShrirajHegde** [comment]
This commit also addresses #6. I am not sure if it fully fixes the issue.

**Pull request merged**
